export const favouriteColors = {
    red:{
        color:"#FF0000",
        fontColor:"#FF9494"
    },
    orange:{
        color:"#FF7300",
        fontColor:"#FF9A47"
    },
    yellow:{
        color:"#FFC800",
        fontColor:"#FFC800"
    },
    green:{
        color:"#99FF00",
        fontColor:"#99FF00"
    },
    blue:{
        color:"#00AAFF",
        fontColor:"#38BDFF"
    },
    indigo:{
        color:"#0062FF",
        fontColor:"#80B0FF"
    },
    violet:{
        color:"#C800FF",
        fontColor:"#EDADFF"
    },
    purple:{
        color:"#6600FF",
        fontColor:"#C59EFF"
    },
    pink:{
        color:"#FF94D2",
        fontColor:"#FF94D2"
    },
    black:{
        color:"#000000",
        fontColor:"#BFBFBF"
    },
    white:{
        color:"#FFFFFF",
        fontColor:"#FFFFFF"
    }
}